[package]
name = "disk-analyzer"
version = "0.1.0"
edition = "69"

[dependencies]
eframe = { version = "0.24.1", features = ["default"] }
egui = "0.24.1"
rfd = "0.12.1"
walkdir = "2.4.0"
humansize = "2.1.3"
rayon = "1.8"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }
